name: ci-auth-test
on:
  workflow_dispatch: {}           # run manually
permissions:
  contents: read
  id-token: write                 # REQUIRED for GitHub→GCP OIDC
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Show active account
        run: |
          gcloud auth list
          gcloud config list

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev -q
