name: Build & Push Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-south1
  AR_REPO: moc-repo
  AR_HOST: asia-south1-docker.pkg.dev
  SERVICES: |
    Authentication-Service
    Real-Time-Communication
    Notification-Service
    To-Do-List-ecosystem
    api-gateway

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Enable Docker to push to Artifact Registry
        run: gcloud auth configure-docker ${{ env.AR_HOST }} -q

      - name: Compute tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & push images with Cloud Build
        shell: bash
        run: |
          IFS=$'\n' read -d '' -r -a SVC_ARR <<< "${SERVICES}"
          for MODULE in "${SVC_ARR[@]}"; do
            NAME=$(basename "$MODULE")
            IMAGE="${AR_HOST}/${GCP_PROJECT_ID}/${AR_REPO}/${NAME}:${{ steps.vars.outputs.TAG }}"
            echo ">>> Building $NAME -> $IMAGE"
            gcloud builds submit --tag "$IMAGE" "$MODULE"
          done

      - name: List pushed images
        run: gcloud artifacts docker images list "${{ env.AR_HOST }}/${{ env.GCP_PROJECT_ID }}/${{ env.AR_REPO }}" --include-tags